config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks do
    member do
      patch :complete
      patch :incomplete
    end
  end 
  root 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

    def completed?
       completed.blank? 
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show,:edit,:update,:destroy]
  
  def index
    @tasks = Task.all.order("created_at DESC")
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(item_params_new)
    if @task.save
      redirect_to root_path
    else 
      format.html {render :new} 
    end

  end

  def show
  end

  def edit
  end

  def update
    if @task.update(item_params)
      redirect_to root_path
    else
      render 'edit'
    end 
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  def complete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed, true)
    redirect_to root_path
  end

  def incomplete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed, false)
    redirect_to root_path
  end

  private

  def item_params_new
    params.permit(:title)
  end 

  def item_params
    params.require(:task).permit(:title)
  end 

  def find_task
     @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>

<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.submit "Enviar",class:"btn btn-primary" %>
</div>



<% end %>

app/views/tasks/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Editar Tarea</h2>
            <%= render 'form', task: @task %>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>To Do</h1>

            <h3>Crear Tarea</h3>

            <%= render 'form', task: @task %>

            <h3>Sus tareas son las siguientes</h3>

            <% @tasks.each do |task| %>
                <% if task.completed?%>
                    <li class="task"> <%= task.title%> 
                    <%= link_to "Editar", edit_task_url(task)%>
                    <%= link_to "Borrar", task_url(task), method: :delete, data:{confirm: "¿Estas seguro?" }, class:"b-button"%>
                    <%= link_to "Completar", complete_task_url(task), method: :patch, class:"a-button"%>
                    </li> 
                <% else %>
                    <li class="data-task"> <%= task.title%> 
                    <%= link_to "Borrar", task_url(task), method: :delete, data:{confirm: "¿Estas seguro?" }, class:"b-button"%>
                    <%= link_to "No Completada", incomplete_task_url(task), method: :patch%>
                    </li> 
                <% end %>
            <% end %>
        </div>
    </div>
</div>